FROM node:16.13.1-alpine as server_dist

WORKDIR /server_dist

# Only copy over the packages files of all required packages.
# This will ensure that we don't have to install all dependencies
# again if any source files change.
COPY package*.json lerna.json tsconfig.json ./
COPY packages/notification/package*.json ./packages/notification/
# Install dependencies and bootstrap packages
RUN npm ci --unsafe-perm

# Now copy over source files and assets
COPY packages/notification/src ./packages/notification/src
COPY packages/notification/tsconfig.json ./packages/notification/
COPY assets/ ./assets
COPY packages/notification/webpack.config.js ./packages/notification/webpack.config.js

RUN npm run notification:build



FROM node:16.13.1 as server_dist2

WORKDIR /server_dist2/packages/notification

COPY --from=server_dist /server_dist/packages/notification/dist/package*.json .

RUN npm install

COPY --from=server_dist /server_dist/packages/notification/dist/ .



FROM node:16.13.1-buster-slim

EXPOSE 5020
ENV PL_ASSETS_DIR=/assets
#ENV PL_ATTACHMENTS_DIR=/attachments
ENV PL_SERVER_CLIENT_URL=http://localhost

WORKDIR /padloc/packages/notification

COPY --from=server_dist2 /server_dist2/packages/notification/ .

ENTRYPOINT ["npm", "run"]

CMD [ "server"]
