
// Objective-C API for talking to the following Go packages
//
//	local_vpn_sdk/cmd/sdk
//	local_vpn_sdk/utils
//
// File is generated by gomobile bind. Do not edit.
#ifndef __LocalVpnSDK_FRAMEWORK_H__
#define __LocalVpnSDK_FRAMEWORK_H__

#include "Local_vpn_sdk.objc.h"
#include "Utils.objc.h"
#include "Universe.objc.h"

#endif
