// Objective-C API for talking to local_vpn_sdk/cmd/sdk Go package.
//   gobind -lang=objc local_vpn_sdk/cmd/sdk
//
// File is generated by gobind. Do not edit.

#ifndef __Local_vpn_sdk_H__
#define __Local_vpn_sdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Utils.objc.h"

FOUNDATION_EXPORT void Local_vpn_sdkLogin(void);

FOUNDATION_EXPORT void Local_vpn_sdkLogout(void);

FOUNDATION_EXPORT void Local_vpn_sdkSDKInitFunc(long fd, NSString* _Nullable loginUrl, NSString* _Nullable authKey, NSString* _Nullable root, NSString* _Nullable cookie, id<UtilsCallback> _Nullable c);

FOUNDATION_EXPORT NSString* _Nonnull Local_vpn_sdkState(void);

FOUNDATION_EXPORT NSString* _Nonnull Local_vpn_sdkStatus(void);

#endif
