// Objective-C API for talking to local_vpn_sdk/utils Go package.
//   gobind -lang=objc local_vpn_sdk/utils
//
// File is generated by gobind. Do not edit.

#ifndef __Utils_H__
#define __Utils_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class UtilsVerbose;
@protocol UtilsCallback;
@class UtilsCallback;

@protocol UtilsCallback <NSObject>
- (void)doCallback:(NSString* _Nullable)s;
- (long)getFd;
- (NSString* _Nonnull)getInterfacesAsString;
- (void)init_:(NSString* _Nullable)s;
- (void)log:(NSString* _Nullable)s;
- (NSString* _Nonnull)readString:(NSString* _Nullable)key;
- (void)setAndroidProtect:(long)fd;
- (void)setRouter:(NSString* _Nullable)addr routers:(NSString* _Nullable)routers;
- (long)updateTun:(NSString* _Nullable)dnsServer searchDomain:(NSString* _Nullable)searchDomain routes:(NSString* _Nullable)routes addrs:(NSString* _Nullable)addrs;
- (void)writeString:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

@interface UtilsVerbose : NSObject <goSeqRefInterface, UtilsCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)doCallback:(NSString* _Nullable)s;
- (long)getFd;
- (NSString* _Nonnull)getInterfacesAsString;
- (void)init_:(NSString* _Nullable)s;
- (void)log:(NSString* _Nullable)s;
- (NSString* _Nonnull)readString:(NSString* _Nullable)key;
- (void)setAndroidProtect:(long)fd;
- (void)setRouter:(NSString* _Nullable)addr routers:(NSString* _Nullable)routers;
- (long)updateTun:(NSString* _Nullable)dnsServer searchDomain:(NSString* _Nullable)searchDomain routes:(NSString* _Nullable)routes addrs:(NSString* _Nullable)addrs;
- (void)writeString:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

FOUNDATION_EXPORT NSString* _Nonnull UtilsAppDir(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT long UtilsParseInt(NSString* _Nullable v);

@class UtilsCallback;

@interface UtilsCallback : NSObject <goSeqRefInterface, UtilsCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)doCallback:(NSString* _Nullable)s;
- (long)getFd;
- (NSString* _Nonnull)getInterfacesAsString;
- (void)init_:(NSString* _Nullable)s;
- (void)log:(NSString* _Nullable)s;
- (NSString* _Nonnull)readString:(NSString* _Nullable)key;
- (void)setAndroidProtect:(long)fd;
- (void)setRouter:(NSString* _Nullable)addr routers:(NSString* _Nullable)routers;
- (long)updateTun:(NSString* _Nullable)dnsServer searchDomain:(NSString* _Nullable)searchDomain routes:(NSString* _Nullable)routes addrs:(NSString* _Nullable)addrs;
- (void)writeString:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

#endif
